# Statistical Methods in Pandas - Lab

## Introduction

In this lesson you'll get some hands-on experience using some of the key summary statistics methods in Pandas.

## Objectives
You will be able to:

* Understand and use the df.describe() and df.info() summary statistics methods
* Use built-in Pandas methods for calculating summary statistics (.mean(), .std(), .count(), .sum(), .mean(), .median(), .std(), .var() and .quantile())
* Apply a function to every element in a Series or DataFrame using s.apply() and df.applymap()


## Getting Started

For this lab, we'll be working with a dataset containing information on various lego datasets.  You will find this dataset in the file `lego_sets.csv`.  

In the cell below:

* Import pandas and set the standard alias of `pd`
* Load in the `lego_sets.csv` dataset using the `read_csv()` function
* Display the head of the DataFrame to get a feel for what we'll be working with

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('lego_sets.csv')

## Getting DataFrame-Level Statistics

We'll begin by getting some overall summary statistics on the dataset.  There are two ways we'll get this information-- `.info()` and `.describe()`.

### Using `.info()`

The `.info()` method provides us metadata on the DataFrame itself.  This allows to answer questions such as:

* What data type does each column contain?
* How many rows are in my dataset? 
* How many total non-missing values does each column contain?
* How much memory does the DataFrame take up?

In the cell below, call our DataFrame's `.info()` method.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 14 columns):
ages                 12261 non-null object
list_price           12261 non-null float64
num_reviews          10641 non-null float64
piece_count          12261 non-null float64
play_star_rating     10486 non-null float64
prod_desc            11884 non-null object
prod_id              12261 non-null float64
prod_long_desc       12261 non-null object
review_difficulty    10206 non-null object
set_name             12261 non-null object
star_rating          10641 non-null float64
theme_name           12258 non-null object
val_star_rating      10466 non-null float64
country              12261 non-null object
dtypes: float64(7), object(7)
memory usage: 1.3+ MB

#### Interpreting the Results

Read the output above, and then answer the following questions:

How many total rows are in this DataFrame?  How many columns contain numeric data? How many contain categorical data?  Identify at least 3 columns that contain missing values. 

Write your answer below this line:
________________________________________________________________________________________________________________________________

## Using `.describe()`

Whereas `.info()` provides statistics about the DataFrame itself, `.describe()` returns output containing basic summary statistics about the data contained with the DataFrame.  

In the cell below, call the DataFrame's `.describe()` method.

In [6]:
df.describe()

,list_price,num_reviews,piece_count,play_star_rating,prod_id,star_rating,val_star_rating
count,12261.000000,10641.000000,12261.000000,10486.000000,1.226100e+04,10641.000000,10466.000000
mean,65.141998,16.826238,493.405921,4.337641,5.983675e+04,4.514134,4.228960
std,91.980429,36.368984,825.364580,0.652051,1.638115e+05,0.518865,0.660282
min,2.272400,1.000000,1.000000,1.000000,6.300000e+02,1.800000,1.000000
25%,19.990000,2.000000,97.000000,4.000000,2.103400e+04,4.300000,4.000000
50%,36.587800,6.000000,216.000000,4.500000,4.206900e+04,4.700000,4.300000
75%,70.192200,13.000000,544.000000,4.800000,7.092200e+04,5.000000,4.700000
max,1104.870000,367.000000,7541.000000,5.000000,2.000431e+06,5.000000,5.000000

#### Interpreting the Results

The output contains descriptive statistics corresponding to the columns.  Use these to answer the following questions:

How much is the standard deviation for piece count?  How many pieces are in the largest lego set?  How many in the smallest lego set? What is the median `val_star_rating`?

________________________________________________________________________________________________________________________________

## Getting Summary Statistics

Pandas also allows us to easily compute individual summary statistics using built-in methods.  Next, we'll get some practice using these methods. 

In the cell below, compute the median value of the `star_rating` column.

In [7]:
df.star_rating.median()

4.7

Next, get a count of the total number of values in `play_star_rating`.

In [8]:
df.play_star_rating.value_counts()

5.0    2219
4.5    1136
4.7     840
4.0     816
4.3     793
4.6     685
4.4     566
4.8     504
4.2     467
4.1     320
3.9     281
3.6     213
4.9     204
3.5     204
3.0     202
3.2     192
3.7     186
3.8     148
2.0     126
3.3     120
2.7      64
1.0      42
2.2      42
2.5      42
3.4      25
2.9      21
2.3      20
3.1       4
2.8       2
2.1       2
Name: play_star_rating, dtype: int64

Now, compute the standard deviation of the `list_price` column.

In [9]:
df.list_price.std()

91.9804293059243

If we bought every single lego set in this dataset, how many pieces would we have?  

> **Note**: If you truly want to answer this accurately, and are up for the challenge, try and remove duplicate lego-set entries before summing the pieces. That is, many of the lego sets are listed multiple times in the dataset above, depending on the country where it is being sold and other unique parameters. If you're stuck, just practice calculating the total number of pieces in the dataset for now.

In [11]:
piece_count = df['piece_count'.sum()
piece_count

,list_price,num_reviews,play_star_rating,prod_id,star_rating,val_star_rating
piece_count,,,,,,
1.0,15647.8445,6191.0,1210.6,11081089.0,1175.5,929.8
2.0,562.4892,2625.0,172.2,305781.0,155.4,107.1
6.0,371.5338,0.0,0.0,683970.0,0.0,0.0
7.0,524.5233,374.0,116.0,2610975.0,112.4,107.6
8.0,717.9444,1669.0,303.6,3596449.0,323.5,278.2
10.0,960.1196,1213.0,102.8,336595.0,101.3,88.5
12.0,26.6822,6.0,10.0,21230.0,10.0,9.4
13.0,66.9266,16.0,24.6,64432.0,27.4,23.6
15.0,1010.6538,63.0,168.0,682290.0,189.0,168.0
16.0,254.1646,0.0,0.0,228270.0,0.0,0.0
18.0,259.2846,0.0,0.0,228018.0,0.0,0.0
19.0,888.8334,21.0,63.0,466719.0,84.0,84.0
22.0,1513.8752,0.0,0.0,456960.0,0.0,0.0
23.0,996.1092,126.0,210.0,455763.0,210.0,205.8
24.0,2756.0090,2121.0,212.1,1064679.0,409.5,212.1
25.0,35.5822,6.0,9.4,21232.0,10.0,9.4
26.0,1668.0968,84.0,210.0,677691.0,210.0,210.0
28.0,2598.3720,128.0,205.3,704346.0,205.3,173.8
29.0,1174.3414,6.0,10.0,476649.0,10.0,9.4
30.0,138.5866,4.0,10.0,1750332.0,10.0,9.0
31.0,756.7876,21.0,105.0,227997.0,105.0,84.0
32.0,621.6546,0.0,0.0,227619.0,0.0,0.0
34.0,747.3046,0.0,0.0,228123.0,0.0,0.0
36.0,494.3646,126.0,100.8,227136.0,105.0,98.7
37.0,910.3022,63.0,199.5,1492008.0,199.5,210.0
38.0,1660.0382,56.0,32.8,1026560.0,34.4,29.6
39.0,584.9190,48.0,113.0,391141.0,113.6,112.4
40.0,177.0745,70.0,45.0,712380.0,46.0,43.0
41.0,385.0446,0.0,0.0,228102.0,0.0,0.0
45.0,369.5880,148.0,80.2,1314967.0,86.4,77.1
...,...,...,...,...,...,...
1977.0,359.3822,36.0,8.6,84108.0,9.6,9.2
1996.0,5113.1496,4221.0,81.9,1576260.0,100.8,94.5
2028.0,4952.0674,1159.0,87.4,1344269.0,91.2,81.7
2049.0,3989.4496,1659.0,100.8,447510.0,105.0,98.7
2262.0,4041.2496,3717.0,92.4,215166.0,96.6,92.4
2294.0,5400.4496,1092.0,69.3,1491882.0,94.5,90.3
2295.0,8661.6992,2184.0,197.4,2965956.0,205.8,201.6
2382.0,7519.5021,2795.0,184.5,1056651.0,196.7,182.2
2455.0,14203.4101,168.0,77.7,42009051.0,71.4,60.9
2464.0,4755.4496,1911.0,102.9,215187.0,102.9,98.7
2469.0,4012.5496,4242.0,98.7,215103.0,102.9,98.7
2480.0,4162.2496,1302.0,92.4,215460.0,96.6,90.3
2526.0,527.3822,94.0,9.0,152104.0,9.2,8.4
2595.0,4123.9496,462.0,94.5,883638.0,98.7,98.7
2631.0,16706.4243,147.0,98.7,42009030.0,96.6,75.6
2670.0,4877.3096,1113.0,88.2,215397.0,92.4,88.2
2704.0,7846.7525,3003.0,88.2,883176.0,98.7,90.3
2863.0,6659.8525,231.0,90.3,443877.0,94.5,88.2
3444.0,14048.5050,798.0,205.8,2978724.0,210.0,205.8
3929.0,6101.6625,1575.0,81.9,883155.0,96.6,96.6
4002.0,6377.1525,2079.0,98.7,215355.0,100.8,94.5
4016.0,12853.0525,1778.0,94.5,1578339.0,81.9,73.5
4080.0,8845.8625,3591.0,94.5,1491840.0,98.7,94.5
4163.0,5924.1496,1344.0,77.7,215313.0,96.6,96.6
4295.0,5953.9296,4788.0,88.2,214494.0,100.8,96.6
4634.0,9205.6525,2730.0,98.7,1592367.0,100.8,98.7
4867.0,15525.9050,3696.0,201.6,2966040.0,205.8,201.6
4900.0,9185.8814,42.0,105.0,42008589.0,105.0,105.0
5923.0,8576.4525,903.0,81.9,215376.0,100.8,94.5
7541.0,20380.2459,4155.0,84.0,1579032.0,100.8,92.4

Now, let's try getting the value for the 90% quantile.  Do this in the cell below.

In [ ]:
# Your code here

## Getting Summary Statistics on Categorical Data

For obvious reasons, most of the methods we've used so far only work with numerical data--there's no way to calculate the standard deviation of a column containing string values. However, there are some things that we can discover about columns containing categorical data. 

In the cell below, get the `.unique()` values contained within the `review_difficulty` column.

In [ ]:
# Your code here

Now, let's get the `value_counts` for this column, to see how common each is.

In [ ]:
# Your code here

As you can see, these provide us quick and easy ways to get information on columns containing categorical information.  


## Using `.applymap()`

When working with pandas DataFrames, we can quickly compute functions on the data contained by using the `applymap()` function and passing in a lambda function. 

For instance, we can use `applymap()` to return a version of the DataFrame where every value has been converted to a string.

In the cell below:

* Call our DataFrame's `.applymap()` function and pass in `lambda x: str(x)`
* Call our new `string_df` object's `.info()` method to confirm that everything has been cast to a string

In [ ]:
string_df = None

Note that everything--even the `NaN` values, has been cast to a string in the example above. 

Note that for pandas Series objects (such as a single column in a DataFrame), we can do the same thing using the `apply()` method.  

This is just one example of how we can quickly compute custom functions on our DataFrame--this will become especially useful when we learn how to **_normalize_** our datasets in a later section!

## Summary

In this lab, we learned how to:

* Understand and use the df.describe() and df.info() summary statistics methods
* Use built-in Pandas methods for calculating summary statistics (.mean(), .std(), .count(), .sum(), .mean(), .median(), .std(), .var() and .quantile())
* Apply a function to every element in a Series or DataFrame using s.apply() and df.applymap()